language: python
python:
    - "2.7.12"
# Install all dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls

services:
    - postgresql
# command to create database
before_script:
    - psql -c 'create database sample_db;' -U postgres
# command to run tests
script:
    -nosetests --with-coverage --cover-erase --cover-package=tests
after_success:
    - coveralls
    
