language: python
python:
    - "3.5.2"
# Install all dependencies
install:
    - pip install -r requirements.txt
    - pip install psycopg2
# command to run tests
script: pytest
after_success:
    - coveralls